/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PertemuanKe4.AplikasiGUI3;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 *
 * @author Rizky Wahyudi
 */
public class AplikasiDataMahasiswa extends javax.swing.JFrame {
    //membuat object dari mahasiswa
    private MahasiswaTableModel model;
    //membuat list untuk menampung data
    private List<Mahasiswa> listData;
    /**
     * Creates new form AplikasiDataMahasiswa
     */
    public AplikasiDataMahasiswa() {
        initComponents();
        //memposisikan table di tengah
        setLocationRelativeTo(null);
        //pengambilan data secara manual
        initData();
        //memasukkan data ke model
        model = new MahasiswaTableModel(listData);
        //memasukkan data dari model ke table mahasiswa
        tableMahasiswa.setModel(model);
    }

    //pembuatan fungsi initData();
    private void initData(){
        //pemanggilan listData
        listData = new ArrayList<>();
        //pembuatan class mahasiswa dan pengisian data ke mahasiswa
        Mahasiswa mahasiswa = new Mahasiswa
            ("43A87006180117", "Rizki Wahyudi", "Teknik Informatika",
                    "Kota Bekasi", "rizukiwahyudio@gmail.com", "085211345481");
        //memasukkan data ke listData mahasiswa
        listData.add(mahasiswa);
        
        //pembuatan data ke dua
        mahasiswa = new Mahasiswa
            ("43A87006180118", "ateng", "Teknik Informatika",
                    "Kota Bogor", "ateng@gmail.com", "08971063039");
        listData.add(mahasiswa);
        
        //pembuatan data ke tiga
        mahasiswa = new Mahasiswa
            ("43A87006180119", "maemunah", "Teknik Informatika",
                    "Kota Cimahi", "mae@gmail.com", "085788783566");
        listData.add(mahasiswa);
        
        //pembuatan data ke empat
        mahasiswa = new Mahasiswa
            ("43A87006180120", "bahrudin", "Teknik Informatika",
                    "Kota Bandung", "bah@gmail.com", "08587651234");
        listData.add(mahasiswa);
        
        //pembuatan data ke lima
        mahasiswa = new Mahasiswa
            ("43A87006180121", "zulkhadafi", "Teknik Informatika",
                    "Kota Makasar", "zul@gmail.com", "08229889900");
        listData.add(mahasiswa);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        buttonTambah = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Data Mahasiswa");

        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMahasiswa.setRowHeight(24);
        tableMahasiswa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableMahasiswa.getTableHeader().setResizingAllowed(false);
        tableMahasiswa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableMahasiswa);

        buttonTambah.setText("Tambah");

        buttonUbah.setText("Ubah");

        buttonHapus.setText("Hapus");

        buttonKeluar.setText("Keluar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonTambah)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUbah)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonUbah)
                        .addComponent(buttonHapus)
                        .addComponent(buttonKeluar))
                    .addComponent(buttonTambah))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiDataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMahasiswa;
    // End of variables declaration//GEN-END:variables
}
